version: '3.1'

services: 
    rest:
        container_name: PartyPlanner.Rest
        image: partyplanner.rest
        build: 
            context: .
            dockerfile: ./PartyPlanner.Rest/Dockerfile
        env_file: .env
        environment: 
            - ConnectionString=$CONN_STRING
            - DatabaseName=$MONGO_INITDB_DATABASE
            - CollectionName=Parties
            - LogFilePath=./logs/rest.log
        ports:
            - "80:80"
            - "443:443"
        volumes: 
            - ./PartyPlanner.Logs/Rest:/app/logs
        depends_on: 
          #            - db
    db:
        container_name: PartyPlanner.DB
        image: mongo
        env_file: .env
        ports: 
            - "27017:27017"
        restart: always
        volumes: 
            - ./PartyPlanner.Database/Scripts/:/docker-entrypoint-initdb.d
            - ./PartyPlanner.Database/Data:/data/db
